# ci-pip.yml
# This workflow is triggered on push or pull request events to the main branch.
# It runs a series of jobs to set up the environment, install dependencies, and run tests.

name: CI with pip
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.GH_PAT }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install .

      - name: Check help menu
        run: estploidy --help
# implement unit tests when available
#      - name: Run tests
#        run: |
#          pytest tests/

# some explicit diff checks on provided test data
#      - name: Create an array of the average allele balance in popultions
#        id: calc-freqs-check
#        run: |
#            estploidy calculate_pop_freqs -i tests/freqs/ex.vcf -o tests/freqs/popfreqs.txt tests/freqs/samplesheet
#            echo "sample output from build"
#            head tests/freqs/popfreqs.txt
#            echo "sample expected output"
#            head tests/freqs/expected_popfreqs.txt
#      - name: Run diff on tests
#        id: diff
#        run: |
#            #compare matrices and throw an exit code if not the same
#            if ! diff -q tests/freqs/popfreqs.txt tests/freqs/expected_popfreqs.txt; then
#                echo "allele frequency matrices do not match!"
#                diff tests/output/popfreqs.txt tests/output/expected_popfreqs.txt
#                exit 1
#            fi
#        shell: bash
        